"""empty message

Revision ID: ba306cf823e4
Revises: d76b2643c895
Create Date: 2021-01-28 11:41:15.021027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba306cf823e4'
down_revision = 'd76b2643c895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('training_type', sa.String(length=100), nullable=True))
    op.add_column('workout', sa.Column('week', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'week')
    op.drop_column('workout', 'training_type')
    # ### end Alembic commands ###
