"""First user and workout tables

Revision ID: f40795e5850c
Revises: 
Create Date: 2021-01-26 09:48:51.114521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40795e5850c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_move', sa.String(length=100), nullable=True),
    sa.Column('main_move_reps', sa.Integer(), nullable=True),
    sa.Column('main_move_sets', sa.Integer(), nullable=True),
    sa.Column('main_move_rpe', sa.Integer(), nullable=True),
    sa.Column('main_move_weight', sa.Integer(), nullable=True),
    sa.Column('assa_move', sa.String(length=100), nullable=True),
    sa.Column('assa_move_reps', sa.Integer(), nullable=True),
    sa.Column('assa_move_sets', sa.Integer(), nullable=True),
    sa.Column('assa_move_rpe', sa.Integer(), nullable=True),
    sa.Column('assa_move_weight', sa.Integer(), nullable=True),
    sa.Column('assb1_move', sa.String(length=100), nullable=True),
    sa.Column('assb1_move_reps', sa.Integer(), nullable=True),
    sa.Column('assb1_move_sets', sa.Integer(), nullable=True),
    sa.Column('assb1_move_rpe', sa.Integer(), nullable=True),
    sa.Column('assb1_move_weight', sa.Integer(), nullable=True),
    sa.Column('assb2_move', sa.String(length=100), nullable=True),
    sa.Column('assb2_move_reps', sa.Integer(), nullable=True),
    sa.Column('assb2_move_sets', sa.Integer(), nullable=True),
    sa.Column('assb2_move_rpe', sa.Integer(), nullable=True),
    sa.Column('assb2_move_weight', sa.Integer(), nullable=True),
    sa.Column('assc1_move', sa.String(length=100), nullable=True),
    sa.Column('assc1_move_reps', sa.Integer(), nullable=True),
    sa.Column('assc1_move_sets', sa.Integer(), nullable=True),
    sa.Column('assc1_move_rpe', sa.Integer(), nullable=True),
    sa.Column('assc1_move_weight', sa.Integer(), nullable=True),
    sa.Column('assc2_move', sa.String(length=100), nullable=True),
    sa.Column('assc2_move_reps', sa.Integer(), nullable=True),
    sa.Column('assc2_move_sets', sa.Integer(), nullable=True),
    sa.Column('assc2_move_rpe', sa.Integer(), nullable=True),
    sa.Column('assc2_move_weight', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=4000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout')
    op.drop_table('user')
    # ### end Alembic commands ###
